language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: peter@superlativecode.com
  api_key:
    secure: S0zJcZ/nSp01b4VMPxQSLtKbmPSOFMq62F+a67MIJKT1nLdKACJGWZfsZBsQqf0TsUNRUqxIgCeOHwdC3veTHCl95rA7CeBQdu6RPJbX3Ms3k5Jvc2eMVzTkzLe708JXn9UkBUJ740JBv93pdwTQ5Z8SRBzC/RENbEnLZi14YPg=
  on:
    tags: true
    repo: peterdemartini/html5-to-pdf
