language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: peter@superlativecode.com
  api_key:
    secure: vVScZhAKkMAFxAYDXgMKUGuoEtCN4ApiWiOTsrorw6rNyTnRVC4fUKCKNR80yd4wwH3aGBaz4Z2eYw6RI5V9crCUO8MqFo0e2KIfwwqx6mIGbf25Zu/rRjMFJEbQfhPRNxdUWLtDttIQ6JMse9P9jUzhLA142vKBjPxOjarEgb4=
  on:
    tags: true
    repo: peterdemartini/html5-to-pdf
