language: node_js
node_js:
- '5'
addons:
  apt:
    packages:
      - build-essential
deploy:
  provider: npm
  email: peter@superlativecode.com
  api_key:
    secure: Die5PT2hkthnpqc2SA/udeM16h7eUe92KIYqglDTWIryTK6VDXs9peT4SyYtdCYZ+Ft8FU/Yq/kCFpHBbOCWflNiCl5BvkoYCEF3MaDkHhSJwfxePq+xntGWwNlCms3qVEOVRmCzvRWvQg/gsFDm7XWa0Qalx0ldS2fIW6Ktzps=
  on:
    tags: true
    repo: peterdemartini/html5-to-pdf
